name: compile-pdf

on:
  page_build:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          #latexmk_use_xelatex: true
      #- name: Publish PDF
       # uses: appleboy/scp-action@v0.1.1
        #with:
         # host: ${{ secrets.SSH_HOST }}
          #username: ${{ secrets.SSH_USERNAME }}
          #key: ${{ secrets.SSH_KEY }}
          #passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          #source: "main.pdf"
          #target: "~/"
          #use_insecure_cipher: true
          
      - run: sudo cp main.pdf /outme
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: /outme/main.pdf
          
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'outme'
          destination-github-username: 'ShantanuDash'
          destination-repository-name: 'cv'
          user-email: me@shantanu.rocks
          target-branch: gh-pages

      #- name: Push to gh-pages
        #uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        #with:
         # files: main.pdf
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITHUB_REPOSITORY: ShantanuDash/cv
        #uses: canastro/copy-file-action@master
        #with:
        #  source: "main.pdf"
        #  target: "shan.pdf"
        #if: success() # && github.event_name == 'push'
        #uses: peaceiris/actions-gh-pages@v3
       # with:
         # github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: ./output
          #user_name: 'github-actions[bot]'
          #user_email: 'github-actions[bot]@users.noreply.github.com'
