name: compile-pdf

on:
  #page_build:
  #pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - run: sudo mkdir outme
      - run: sudo cp main.pdf outme   
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'outme'
          destination-github-username: 'ShantanuDash'
          destination-repository-name: 'cv'
          user-email: me@shantanu.rocks
          target-branch: gh-pages
      #- name: convert pdf to png
      - run: sudo apt install poppler-utils
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install pdf2image
      - run: python my_script.py
      - run: sudo mkdir outpng
      #- run: pdftoppm main.pdf main -png -rx 300 -ry 300
      - run: sudo cp main.png outpng
        
      
      - name: Push png to ShantanuDash
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'outpng'
          destination-github-username: 'ShantanuDash'
          destination-repository-name: 'ShantanuDash'
          user-email: me@shantanu.rocks
          target-branch: main
          
      - name: upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: outme/main.pdf
      - name: upload img
        uses: actions/upload-artifact@v2
        with:
          name: IMG
          path: outpng/main.png    

