name: compile-pdf

on:
  page_build:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          #latexmk_use_xelatex: true
          
      - name: Push to gh-pages
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ShantanuDash/cv
        #uses: canastro/copy-file-action@master
        #with:
        #  source: "main.pdf"
        #  target: "shan.pdf"
        #if: success() # && github.event_name == 'push'
        #uses: peaceiris/actions-gh-pages@v3
       # with:
         # github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: ./output
          #user_name: 'github-actions[bot]'
          #user_email: 'github-actions[bot]@users.noreply.github.com'
